# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "api"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "ACCOUNT_DATABASE"
database_name = "api-db"
database_id = "your-d1-database-id-here"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "ACCOUNT_KV"
id = "your-kv-namespace-id-here"


# To protect the database id, kv id, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml